default_job = "build_lib"
ignore = "**/.*.swp"

[jobs.build_lib]
command = ["cargo", "build", "--color", "always", "-p", "tiger-lib"]
need_stdout = false

[jobs.build_ck3]
command = ["cargo", "build", "--color", "always", "-p", "ck3-tiger"]
need_stdout = false

[jobs.build_vic3]
command = ["cargo", "build", "--color", "always", "-p", "vic3-tiger"]
need_stdout = false

[jobs.build_imperator]
command = ["cargo", "build", "--color", "always", "-p", "imperator-tiger"]
need_stdout = false

[jobs.build_hoi4]
command = ["cargo", "build", "--color", "always", "-p", "hoi4-tiger"]
need_stdout = false

[jobs.clippy_lib]
command = ["cargo", "clippy", "--color", "always", "-p", "tiger-lib"]
need_stdout = false

[jobs.clippy_ck3]
command = ["cargo", "clippy", "--color", "always", "-p", "ck3-tiger"]
need_stdout = false

[jobs.clippy_vic3]
command = ["cargo", "clippy", "--color", "always", "-p", "vic3-tiger"]
need_stdout = false

[jobs.clippy_imperator]
command = ["cargo", "clippy", "--color", "always", "-p", "imperator-tiger"]
need_stdout = false

[jobs.clippy_hoi4]
command = ["cargo", "clippy", "--color", "always", "-p", "hoi4-tiger"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true

[jobs.docs]
command = ["cargo", "doc", "--color", "always", "--features", "ck3 vic3 imperator", "--no-deps", "--document-private-items"]
need_stdout = false

[keybindings]
"`" = "job:build_lib"
1 = "job:build_ck3"
2 = "job:build_vic3"
3 = "job:build_imperator"
4 = "job:build_hoi4"
"~" = "job:clippy_lib"
"!" = "job:clippy_ck3"
"@" = "job:clippy_vic3"
"#" = "job:clippy_imperator"
"$" = "job:clippy_hoi4"
"d" = "job:docs"
