[package]
name = "ck3-mod-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bitflags = "1.3.2"
clap = { version = "3", features = ["derive"] }
encoding = "0.2"
fnv = "1"
home = "0.5"
image = "0.24"
itertools = "0.10"
lazy_static = "1"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1"
unicode-width = "0.1.9"
walkdir = "2"

[target.'cfg(windows)'.dependencies]
winreg = "0.10"
