on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Quality Assurance

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
    name: ${{ matrix.name }} test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Test
        run: cargo test

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: fmt
        run: cargo fmt --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: CK3 clippy
        run: cargo clippy -p ck3-tiger

      - name: Vic3 clippy
        run: cargo clippy -p vic3-tiger

      - name: Imperator clippy
        run: cargo clippy -p imperator-tiger

      - name: utils clippy
        run: cargo clippy -p utils

  msrv:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
    name: ${{ matrix.name }} msrv
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
          toolchain: 1.75

      - name: tiger-lib msrv
        run: cargo check

      - name: CK3 msrv
        run: cargo check -p ck3-tiger

      - name: Vic3 msrv
        run: cargo check -p vic3-tiger

      - name: Imperator msrv
        run: cargo check -p imperator-tiger
